USE Library;

INSERT INTO Books (BookBarcode, Title, Publisher, PublicationDate, BookEdition,
                    BookLanguage, Genre, AvailabilityStatus, CallNumber)
VALUES
('852112308018', 'A Brief History of Time', 
(SELECT ID from Publishers where PublisherName = 'Bantam Books'),
'1998-09-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Science'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'523.1'),

('1061988575523', 'Introduction to Algorithms', 
(SELECT ID from Publishers where PublisherName = 'MIT Press'),
'1989-01-01', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Science'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'005.1'),

('126620977745', 'The Origin of Species', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'2003-09-02', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Science'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'575.0162'),

('113249352922', 'Relativity: The Special and the General Theory', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'2006-06-25', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Science'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'530.112'),

('109584146703', 'Astrophysics for People in a Hurry', 
(SELECT ID from Publishers where PublisherName = 'W. W. Norton & Company'),
'2017-05-02', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Science'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'523.01'),

('451973311060', 'The Little Prince', 
(SELECT ID from Publishers where PublisherName = 'Harcourt'),
'2000-05-15', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Childrens lit.'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'843.912'),

('103044064583', 'Le Petit Prince', 
(SELECT ID from Publishers where PublisherName = 'Folio Junior'),
'1998-01-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'French'), 
(SELECT ID from BookGenres where Genre = 'Childrens lit.'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'843.912'),

('621844182299', 'The Lion, the Witch and the Wardrobe', 
(SELECT ID from Publishers where PublisherName = 'Harper Collins'),
'2013-01-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Childrens lit.'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'823.087661'),

('1093889941888', 'The Lightning Thief', 
(SELECT ID from Publishers where PublisherName = 'Disney-Hyperion Books'),
'2006-03-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Childrens lit.'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.6'),

('298941326779', 'The Sea of Monsters', 
(SELECT ID from Publishers where PublisherName = 'Disney-Hyperion Books'),
'2006-05-01', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Childrens lit.'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.6'),

('684329975194', 'The Hunger Games', 
(SELECT ID from Publishers where PublisherName = 'Scholastic Press'),
'2008-10-14', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Young Adult'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.6'),

('295765267472', 'Catching Fire', 
(SELECT ID from Publishers where PublisherName = 'Scholastic Press'),
'2009-09-01', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Young Adult'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.6'),

('1008747063973', 'Mockingjay', 
(SELECT ID from Publishers where PublisherName = 'Scholastic Press'),
'2010-08-24', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Young Adult'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.6'),

('658137374877', 'Eragon', 
(SELECT ID from Publishers where PublisherName = 'Knopf Books'),
'2005-06-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Young Adult'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.6'),

('602432211917', 'Eldest', 
(SELECT ID from Publishers where PublisherName = 'Knopf Books'),
'2007-03-13', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Young Adult'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.6'),

('389361461145', 'House of Leaves', 
(SELECT ID from Publishers where PublisherName = 'Random House'),
'2000-03-07', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Horror'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.54'),

('1020681036880', 'Dracula', 
(SELECT ID from Publishers where PublisherName = 'Barnes & Noble'),
'2011-03-01', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Horror'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'823.087381'),

('611308683901', 'The Picture of Dorian Gray', 
(SELECT ID from Publishers where PublisherName = 'Random House'),
'2004-06-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Horror'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'823.8'),

('370140854718', 'The Tell-Tale Heart', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'2015-02-26', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Horror'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.3'),

('240031867881', 'The Cask of Amontillado', 
(SELECT ID from Publishers where PublisherName = 'BookSurge'),
'2009-04-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Horror'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.3'),

('208913198036', 'The Prince', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'2003-02-04', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Philosophy'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'320.1'),

('633438264582', 'The Republic', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'2003-02-25', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Philosophy'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'321.07'),

('402050855286', 'Leviathan', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'1981-11-19', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Philosophy'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'320.1'),

('370934540842', 'Beyond Good and Evil', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'2003-04-29', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Philosophy'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'193'),

('345922611896', 'Critique of Pure Reason', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'1999-02-28', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Philosophy'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'121'),

('916922412061', 'A Midsummer Nights Dream', 
(SELECT ID from Publishers where PublisherName = 'Simon & Schuster'),
'2016-07-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Classics'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'822.33'),

('1064950153993', 'Hamlet', 
(SELECT ID from Publishers where PublisherName = 'Cambridge University Press'),
'2005-12-19', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Classics'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'822.33'),

('372760222061', 'The Iliad', 
(SELECT ID from Publishers where PublisherName = 'W. W. Norton & Company'),
'2023-09-26', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Classics'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'883.01'),

('789676336797', 'The Odyssey', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'2006-10-31', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Classics'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'883.01'),

('1071580139839', 'Antigone', 
(SELECT ID from Publishers where PublisherName = 'Prestwick House'),
'2005-11-30', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Classics'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'882.01'),

('945875270706', 'The Silmarillion', 
(SELECT ID from Publishers where PublisherName = 'Harper Collins'),
'2011-02-03', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Fantasy'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'823.087661'),

('776647164311', 'The Fellowship of the Ring', 
(SELECT ID from Publishers where PublisherName = 'William Morrow'),
'2022-06-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Fantasy'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'823.912'),

('994157564023', 'A Wizard of Earthsea', 
(SELECT ID from Publishers where PublisherName = 'Harper Collins'),
'2012-09-11', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Fantasy'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.087661'),

('504792120075', 'Words of Radiance', 
(SELECT ID from Publishers where PublisherName = 'Tor Books'),
'2014-03-04', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Fantasy'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.6'),

('1066363464544', 'The Way of Kings', 
(SELECT ID from Publishers where PublisherName = 'Tor Books'),
'2010-08-31', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Fantasy'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.6'),

('411974140204', 'Shakespeares Sonnets', 
(SELECT ID from Publishers where PublisherName = 'Bloomsbury Arden Shakespeare'),
'1997-08-21', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Poetry'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'821.3'),

('656593744147', 'Paradise Lost', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'2003-04-29', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Poetry'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'821.4'),

('586090281027', 'Aniara', 
(SELECT ID from Publishers where PublisherName = 'Story Line Press'),
'1998-09-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Poetry'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'839.71'),

('323361697799', 'Sentimento do Mundo', 
(SELECT ID from Publishers where PublisherName = 'Companhia das Letras'),
'2012-01-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'Portuguese'), 
(SELECT ID from BookGenres where Genre = 'Poetry'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'869.915'),

('644251809883', 'The Divine Comedy - Volume 1: Hell', 
(SELECT ID from Publishers where PublisherName = 'Penguin Classics'),
'1999-07-12', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Poetry'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'851.1'),

('774529770221', 'Do Androids Dream of Electric Sheep?', 
(SELECT ID from Publishers where PublisherName = 'Ballantine Books'),
'2008-02-26', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Science Fiction'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.0876220'),

('184943603669', 'I, Robot', 
(SELECT ID from Publishers where PublisherName = 'Bantam Books'),
'2004-06-01', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Science Fiction'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.08762'),

('828075047644', 'Dune', 
(SELECT ID from Publishers where PublisherName = 'Ace'),
'2019-10-01', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Science Fiction'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.087625'),

('239259338629', 'The Left Hand of Darkness', 
(SELECT ID from Publishers where PublisherName = 'Ace'),
'2000-07-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Science Fiction'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.54'),

('606447069939', 'Blindsight', 
(SELECT ID from Publishers where PublisherName = 'Tor Books'),
'2006-10-03', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Science Fiction'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'813.6'),

('471381922983', 'Alan Turing: The Enigma', 
(SELECT ID from Publishers where PublisherName = 'Walker Books'),
'2000-03-01', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Biographies'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'510.92'),

('1014704193469', 'J.R.R. Tolkien: A Biography', 
(SELECT ID from Publishers where PublisherName = 'William Morrow'),
'2000-06-06', 'Paperback',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Biographies'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'828.912'),

('1023486141416', 'The Secret Life of Houdini: The Making of Americas First Superhero', 
(SELECT ID from Publishers where PublisherName = 'Atria'),
'2006-10-31', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Biographies'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'793.8092'),

('352402167332', 'Frida: A Biography of Frida Kahlo', 
(SELECT ID from Publishers where PublisherName = 'Harper Collins'),
'2002-10-01', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Biographies'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'759.972'),

('157809483843', 'Einstein: His Life and Universe', 
(SELECT ID from Publishers where PublisherName = 'Simon & Schuster'),
'2007-04-10', 'Hardcover',
(SELECT ID from Languages where BookLanguage = 'English'), 
(SELECT ID from BookGenres where Genre = 'Biographies'), 
(SELECT ID from AvailabilityStatuses where AvailStatus = 'Available'), 
'530.092')