USE Library;

INSERT INTO Authors(FirstName, LastName, Email, Phone, Website)
VALUES    
('Stephen', 'W. Hawking', 'N/A', 'N/A', 'https://www.hawking.org.uk/'),
('Thomas', 'H. Cormen', 'thc@cs.dartmouth.edu', 'N/A', 'https://www.cs.dartmouth.edu/~thc/'),
('Charles', 'E. Leiserson', 'N/A', 'N/A', 'https://people.csail.mit.edu/cel/'),
('Ronald', 'L. Rivest', 'rivest@mit.edu', '617-253-5880', 'https://people.csail.mit.edu/rivest/'),
('Clifford', 'Stein', 'cliff@ieor.columbia.edu', '(212) 854-5238', 'https://www.columbia.edu/~cs2035/'),
('Charles', 'Darwin', 'N/A', 'N/A', 'N/A'),
('Albert', 'Einstein', 'N/A', 'N/A', 'N/A'),
('Neil', 'deGrasse Tyson', 'N/A', 'N/A', 'https://neildegrassetyson.com/'),
('Antoine', 'de Saint-Exupéry', 'N/A', 'N/A', 'https://www.antoinedesaintexupery.org/'),
('C.S.', 'Lewis', 'N/A', 'N/A', 'https://harpercollins.co.uk/pages/cslewis'),
('Rick', 'Riordan', 'N/A', 'N/A', 'https://rickriordan.com/'),
('Suzanne', 'Collins', 'N/A', 'N/A', 'https://www.suzannecollinsbooks.com/'),
('Christopher', 'Paolini', 'N/A', 'N/A', 'https://www.paolini.net/'),
('Mark', 'Z. Danielewski', 'N/A', 'N/A', 'https://www.markzdanielewski.com/'),
('Bram', 'Stoker', 'N/A', 'N/A', 'N/A'),
('Oscar', 'Wilde', 'N/A', 'N/A', 'N/A'),
('Edgar', 'Allan Poe', 'N/A', 'N/A', 'N/A'),
('Niccolò', 'Machiavelli', 'N/A', 'N/A', 'N/A'),
('Plato', ' ', 'N/A', 'N/A', 'N/A'),
('Thomas', 'Hobbes', 'N/A', 'N/A', 'N/A'),
('Friedrich', 'Nietzsche', 'N/A', 'N/A', 'N/A'),
('Immanuel', 'Kant', 'N/A', 'N/A', 'N/A'),
('William', 'Shakespeare', 'N/A', 'N/A', 'N/A'),
('Homer', ' ', 'N/A', 'N/A', 'N/A'),
('Sophocles', ' ', 'N/A', 'N/A', 'N/A'),
('J.R.R', 'Tolkien', 'N/A', 'N/A', 'https://www.tolkienestate.com/'),
('Ursula', 'K. Le Guin', 'N/A', 'N/A', 'https://www.ursulakleguin.com/'),
('Brandon', 'Sanderson', 'N/A', 'N/A', 'https://www.brandonsanderson.com/'),
('John', 'Milton', 'N/A', 'N/A', 'N/A'),
('Harry', 'Martinson', 'N/A', 'N/A', 'N/A'),
('Carlos', 'Drummond de Andrade', 'N/A', 'N/A', 'http://www.carlosdrummond.com.br/'),
('Dante', 'Alighieri', 'N/A', 'N/A', 'N/A'),
('Philip', 'K. Dick', 'N/A', 'N/A', 'N/A'),
('Isaac', 'Asimov', 'N/A', 'N/A', 'N/A'),
('Frank', 'Herbert', 'N/A', 'N/A', 'N/A'),
('Peter', 'Watts', 'N/A', 'N/A', 'https://www.rifters.com/'),
('Andrew', 'Hodges', 'andrew@synth.co.uk', 'N/A', 'https://www.synth.co.uk/'),
('Douglas', 'R. Hofstadter', 'N/A', 'N/A', 'N/A'),
('Humphrey', 'Carpenter', 'N/A', 'N/A', 'N/A'),
('William', 'Kalush', 'N/A', 'N/A', 'N/A'),
('Larry', 'Sloman', 'N/A', 'N/A', 'http://www.ratso.org/ '),
('Hayden', 'Herrera', 'N/A', 'N/A', 'N/A'),
('Walter', 'Isaacson', 'N/A', 'N/A', 'N/A')