USE Library;

-- information on languages with most native speakers
-- from https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers
INSERT INTO Languages (BookLanguage)
VALUES
('English'),
('Mandarin Chinese'),
('Hindi'), 
('Spanish'),
('Modern Standard Arabic'),
('French'),
('Bengali'),
('Portuguese'),
('Indonesian'),
('Urdu'),
('Russian'),
('German'),
('Japanese'),
('Nigerian Pidgin'),
('Egyptian Arab'),
('Marathi'),
('Vietnamese'),
('Telugu'),
('Swahili'),
('Hausa'),
('Turkish'),
('Western Punjabi'),
('Tagalog'),
('Tamil'),
('Yue Chinese'),
('Wu Chinese'),
('Iranian Persian'),
('Korean'),
('Amharic'),
('Thai'),
('Javanese'),
('Italian'),
('Gujarati'),
('Kannada'),
('Levantine Arab'),
('Sudanese Arab'),
('Yoruba'),
('Bhojpuri')